// <auto-generated />
using Lottery.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lottery.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(OnLineDbContext))]
    [Migration("20180618115701_Update_UserTable")]
    partial class Update_UserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lottery.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("CardPassword")
                        .IsRequired();

                    b.Property<string>("CardSalt")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Introducer");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Realname")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasAlternateKey("Account")
                        .HasName("AlternateKey_Account");

                    b.HasIndex("Account")
                        .HasName("Index_Account");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Lottery.Model.Visitors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<Guid>("Uid");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });
#pragma warning restore 612, 618
        }
    }
}
